server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onboarding_db
    username: root
    password: 921111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: irshadwnl07@gmail.com
    password: qfjqxicezkapomwp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

rabbitmq:
  host: localhost
  port: 5672


jwt:
  secret: Msqepcx7Bc02gvA5tRWeQ5KkkOSvZRWiLjtM4VCRqb4=
